### ISSUE TITLE
Create a new environment

### ISSUE THREAD

**Issue by epris** [stanfordnmbl/osim-rl#169]
Dear all,

We are evaluating to use OpenSim and Osim-rl for our research (In the past we used another framework).

If I understand well, at the moment osim-rl is equipped with 3 environments: the arm, the NIPS 2017 and the NIPS 2018.

I want to know if It is possible for an user to add a new environment starting from one of the models created for OpenSim and available on simtk. (I mean on my local machine. Is the use of crowdAI useful only for the competition?)

Why is Arm2dEnv considered a Toy model? For the number of muscles or for the model of muscles?

Best regards,
Antonio

**Comment by kidzik** [comment]
That's true, crowdAI part is only for the competition and you can use our library for other projects.
In order to implement a new model you basically need to:
* create an opensim model 
* create a class inheriting from OsimEnv
* override a couple of methods: `get_observation`, `reward`, 'is_done'
Here is a short example
https://github.com/stanfordnmbl/osim-rl/blob/master/examples/under-construction/walker.py

We call the `Arm2dEnv` a toy model because the range of motion is very limited. Also, it was designed for throwing something rather than for grasping.
