### ISSUE TITLE
two submission options return different evaluation result.

### ISSUE THREAD

**Issue by hanszeng** [stanfordnmbl/osim-rl#199]
I test a same model, but two submission options (docker/server) return different evaluation result.

**Comment by spMohanty** [comment]
@hanszeng : Can you point us to both the submissions ?
We can re-confirm if there are any differences in the configuration.

**Comment by hanszeng** [comment]
Submissions ID: 12668 & 13281

**Comment by hanszeng** [comment]
@spMohanty Hi, have you find out the reason?

**Comment by hanszeng** [comment]
Is it due to the different versions of osim-rl?

**Comment by kiwi-byte** [comment]
Same issue, but I found that submitting by the docker image got the same score as the previous environment(before [55db058](https://github.com/stanfordnmbl/osim-rl/commit/55db058307cb60ffdc9852350f912e4bb317c411)).

So I presume that the docker evaluation environment is still using the old version of `osim-rl`, which means that the maximum score could be 300, much larger than score the current version, 210. 

It could be a serious problem. 
@spMohanty Could you check the version of `osim-rl `in the docker environment ?

**Comment by spMohanty** [comment]
Sorry for the delay here. But confirming that the code-based submissions were being evaluated using version `3.0.5` and the remote submissions were being evaluated with version `3.0.6`.

We are in the process of updating the code based submission evaluators to version 3.0.6, and then we will re-evaluate all the submissions which have been made since the 3.0.6 release. We will post another confirmation here after the all the re-evaluations are done. cc. @skbly7

@smsong  Can you please push a new tag/release for version 3.0.6 on github. I had already released it on PyPI. 

Sorry for the inconvenience and confusion because of this.
