### ISSUE TITLE
Loco_reflex_song2019 controller doesn't work in 3D mode

### ISSUE THREAD

**Issue by FelixDucret** [stanfordnmbl/osim-rl#232]
Hi,

I have tried to use the loco_reflex_song2019 controller defined in the osim-rl/envs/control/loco_reflex_song2019.py file by running the simL2M2019_controller1.py file in both 2D and 3D mode. It seems to be working fine in 2D mode, but the model can't make a step in 3D mode. Is this a bug or are the parameters indicated in osim-rl/osim/control/params_3D_init.txt not viable for three-dimensional locomotion?

Thank you!

**Comment by smsong** [comment]
This is because params_3D_init.txt is not viable to produce successful walking in 3D. params_3D_init.txt is a copy of params_2D.txt with some placeholders (the last 9 parameters with the value of 1.00) for the additional parameters for the 3D controller. We did not have enough time to find successful parameters for 3D back when we uploaded the controller and did not work on it since then.

**Comment by FelixDucret** [comment]
All right, thank you for your answer!
