### ISSUE TITLE
Joint angles duplicated, velocities and the left psoas not present

### ISSUE THREAD

**Issue by ctmakro** [stanfordnmbl/osim-rl#31]
<https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L123-L124>

```py
joint_angles = [self.osim_model.get_joint(jnts[i]).getCoordinate().getValue(self.osim_model.state) for i in range(6)]
joint_vel = [self.osim_model.get_joint(jnts[i]).getCoordinate().getValue(self.osim_model.state) for i in range(6)]
```

they seem identical to me.

**Comment by ctmakro** [comment]
and it would be great to have contact force as a feature, with which our agent can learn to walk on rough surfaces.

**Comment by kidzik** [comment]
Unfortunately, this indeed seems to be a typo. I will check it with the team and we will figure out how to harmlessly modify the environment. Thanks!

**Comment by AdamStelmaszczyk** [comment]
Similar a little below, https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L138:

```
muscles = [ self.env_desc['muscles'][self.MUSCLES_PSOAS_R], self.env_desc['muscles'][self.MUSCLES_PSOAS_R] ]
```

Shouldn't it be:

```
muscles = [ self.env_desc['muscles'][self.MUSCLES_PSOAS_L], self.env_desc['muscles'][self.MUSCLES_PSOAS_R] ]
```

**Comment by ctmakro** [comment]
off the topic: whoever wrote this must have little sleep

**Comment by kidzik** [comment]
Thank you, both for these reports. We decided to modify the environment:
https://github.com/stanfordnmbl/osim-rl/tree/iss31
Fortunately, changes are only adding new information and therefore the models trained before should still work (with a slight modification of the observation vector, which we will describe). Retraining a model with extra information should yield better results.

Changes:

* added velocities of joints in `joint_vel`
* added the left psoas in `muscles`
* moved obstacles closer to the starting point (so that it's easier to train on them)
* extended the trials to 1000 iterations (if they don't trip/fall earlier as it was before)

Soon we will merge the branch and roll out the updated grader. Sorry for the inconvenience.

**Comment by kidzik** [comment]
We updated the environment and wrote some release notes, thanks for your reports! https://github.com/stanfordnmbl/osim-rl/tree/master/docs
