### ISSUE TITLE
Simulation running at <10fps, is that normal?

### ISSUE THREAD

**Issue by ctmakro** [stanfordnmbl/osim-rl#33]
Training takes forever.

**Comment by AdamStelmaszczyk** [comment]
I got around 3 FPS on Lenovo T520.

But, you don't need to visualize when training.

**Comment by kidzik** [comment]
Yes, definitely the visualizer is not needed in training. It should also run a bit faster with no obstacles (`difficulty=0`) and since they don't appear early anyway it's good for the first models. Also, I suggest making the episodes even shorter at the beginning. 
But indeed, the environment is computationally expensive, that's a part of the problem.
