### ISSUE TITLE
Pickling RunEnv

### ISSUE THREAD

**Issue by GolovanovSrg** [stanfordnmbl/osim-rl#63]
How to serialize state of environment to correct restore saved state later?
If I remove pelvis from dict in __getstate__ and pickle the dict, will it work?

**Comment by kidzik** [comment]
Can you please explain your use case in more details? Are you trying to store the description of the environment (obstacles + muscles) or the state of the dynamic system? For now, there is no good interface for the second case (although it is possible).
However, since there is no stochasticity in the current dynamic system, you can just rerun the environment. So there should be no direct necessity for storing the state.

**Comment by GolovanovSrg** [comment]
I want use planning in addition to main model.

**Comment by kidzik** [comment]
This is actually not supported through the python interface. It should be possible to do though if you hack OpenSim -- it's ok regarding the rules of the challenge and we welcome any contributions

For the moment, you can only recreate an environment with the same muscles and obstacles. The description of the environment is available here https://github.com/stanfordnmbl/osim-rl/blob/master/osim/env/run.py#L27 and it is updated by the `setup` function.

Sorry for the late response!
